### ISSUE TITLE
[IoT Health] Test on Jetson Nano

### ISSUE THREAD

**Issue by burpeesDaily** [iot-spectator/iot-health#23]
- Test IoT Health on Jetson Nano
- Implement missing features if there is any

- [x] After the verification, add Jetson Nano as a  supported and tested platform in `README`

**Comment by Cipherman** [comment]
The current lastest SDK for  the Jetson Nano is Jetpack 4.5, which has the spec of
- Ubuntu 18.04
- Python 3.6

For running iothealth package, installation of Python 3.7+ is requried.

The temperature information path is different from other supporting platforms and an issue has been created:

[IoT Health] Temperature polling for Jetpack 4.5 on Jetson Nano #24
https://github.com/iot-spectator/iot-health/issues/24
 
We Will proceed to fix this issue before closing this issue.
