### ISSUE TITLE
[IoT Health] Temperature polling for Jetpack 4.5 on Jetson Nano

### ISSUE THREAD

**Issue by Cipherman** [iot-spectator/iot-health#24]
The polling path for Jetpack 4.5 on Jetson Nano is different from the currently supported platforms. Need to update for Jetson support.

**Comment by Cipherman** [comment]
The path mentioned in the following link works:

https://forums.developer.nvidia.com/t/jetson-nano-monitoring-the-temperature-via-python/83739

/sys/devices/virtual/thermal/thermal_zone*/temp

**Comment by burpeesDaily** [comment]
In this case, you may want to create a new module, `jetson_nano.py`, and follow the `raspberry_pi.py` style. 
These modules may become very similar, but we can refractory the layout later.

**Comment by Cipherman** [comment]
No individual module was created for Jetson Nano in the end, as most of the functions are the same for Linux as well.
